---
# docker-compose.dryrun.yml

services:
  binance:
    extends:
      file: docker-compose.base.yml
      service: common
    container_name: ft_binance_dryrun
    ports:
      - "${PORT_BINANCE_DRY:-8981}:8080"
    command: >
      trade
      --dry-run
      --config user_data/config-binance.json
      --db-url sqlite:////freqtrade/user_data/tradesv3_binance_dryrun.sqlite
      --log-file user_data/logs/binance_dryrun.log
      --strategy-path .

  okx:
    extends:
      file: docker-compose.base.yml
      service: common
    container_name: ft_okx_dryrun
    ports:
      - "${PORT_OKX_DRY:-8989}:8080"
    command: >
      trade
      --dry-run
      --config user_data/config-okx.json
      --db-url sqlite:////freqtrade/user_data/tradesv3_okx_dryrun.sqlite
      --log-file user_data/logs/okx_dryrun.log
      --strategy-path .
