---
# docker-compose.live.yml

services:
  binance:
    extends:
      file: docker-compose.base.yml
      service: common
    container_name: ft_binance_live
    ports:
      - "${PORT_BINANCE_LIVE:-8082}:8080"
    command: >
      trade
      --config user_data/config-binance.json
      --db-url sqlite:////freqtrade/user_data/tradesv3_binance_live.sqlite
      --log-file user_data/logs/binance_live.log
      --strategy-path .

  okx:
    extends:
      file: docker-compose.base.yml
      service: common
    container_name: ft_okx_live
    ports:
      - "${PORT_OKX_LIVE:-8083}:8080"
    command: >
      trade
      --config user_data/config-okx.json
      --db-url sqlite:////freqtrade/user_data/tradesv3_okx_live.sqlite
      --log-file user_data/logs/okx_live.log
      --strategy-path .
